// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU7G-rUNYFIrA7KXA58Zq4_kD2iRzOxcE',
    appId: '1:99643965343:web:c1b639c4cf8dbb4bd8c7aa',
    messagingSenderId: '99643965343',
    projectId: 'lekhny-2ead3',
    authDomain: 'lekhny-2ead3.firebaseapp.com',
    storageBucket: 'lekhny-2ead3.appspot.com',
    measurementId: 'G-TNYJTS2B13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBurb_ws1jFfvIzFGtk5gUQsaFQEyCtvx0',
    appId: '1:99643965343:android:8172e3ab8f0bbb11d8c7aa',
    messagingSenderId: '99643965343',
    projectId: 'lekhny-2ead3',
    storageBucket: 'lekhny-2ead3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUoIU9B9o26q-SNsOALl620OXCN9fyqV8',
    appId: '1:99643965343:ios:ec2324ac72689680d8c7aa',
    messagingSenderId: '99643965343',
    projectId: 'lekhny-2ead3',
    storageBucket: 'lekhny-2ead3.appspot.com',
    iosClientId: '99643965343-fam5mpuqojc3l9hl5q7mkdlmu5tpg04d.apps.googleusercontent.com',
    iosBundleId: 'com.lekhny.lekhnyapp',
  );
}
